version: '2'
services:
  web:
    image: $REGISTRY:$TAG
    build:
      context: .
      args:
        TAG_VERSION_ARG: $TAG
    ports:
     - "80"
    cpu_shares: 400
    environment:
     - REDIS_HOST=$REDIS_HOST
    mem_limit: 134217728
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: ch-group