version: '2'
services:
  web:
    build: .
    volumes:  
     - ./application:/application
    networks:
     - backend
    ports:
     - "8000:80"
  redis:
    image: "redis:alpine"
    cpu_shares: 128
    mem_limit: 134217728
    networks:
     - backend
networks:
  backend: